# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TiendaDeTuna' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

  # Pods for TiendaDeTuna

  target 'TiendaDeTunaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TiendaDeTunaUITests' do
    # Pods for testing
  end

end
